[package]
name = "amba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
s2e = { path = "../s2e" }
cxx = "1.0" # Underspecified to make sure it's compatible with autocxx's cxx version
