[package]
name = "amba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
ctrlc = "3"
home = "0.5"
regex = "1"
serde = { version = "1", features = ["derive"] }
tar = "0.4"
tera = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
ureq = "2"
url = "2"
xz2 = "0.1"
