[package]
name = "disassembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.19"
capstone = "0.11"
elsa = "1"
thiserror = "1"
