main.pdf: \
  main.tex \
  1_bakgrund.tex \
  2_syfte.tex \
  3_problem.tex \
  4_avgransningar.tex \
  5_metod.tex \
  6_etik.tex \
  7_tidsplan.tex \
  refs.bib
	tectonic main.tex
	mv main.pdf bsc_thesis.pdf
