group_64_project_report.pdf: \
  main.tex \
  cover.tex \
  titlepage.tex \
  begreppslista.tex \
  inledning.tex \
  bakgrund.tex \
  binaranalys.tex \
  problem.tex \
  metod.tex \
  amba.tex \
  resultat.tex \
  diskussion.tex \
  slutsatser.tex \
  refs.bib
	tectonic main.tex
	mv main.pdf group_64_project_report.pdf
