name: nix-ci-cachix


on:
  pull_request:
  push:
    branches:
      - master
      - ci
      - autocxx


jobs:

  checks:
    name: Checks
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v20
        with:
          nix_conf: |
            experimental-features = nix-command flakes

      # - uses: cachix/cachix-action@v12
        # with:
          # name: nixbuild
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      - name: Build Nix flake checks
        # working-directory: thesis-decompilation
        # We could use `nix flake check` here, but we build in the same way
        # as the `nix-ci-nixbuild` workflow to be able to compare build times
        run: |
          nix build -L
