# NOTE: Our CI runs on a persistent nix-enabled self hosted server.
# NOTE: Talk to Loke before/when doing significant changes to the CI workload.

name: self-hosted-nix-ci

on:
  push:
    paths:
      - '**'
      - '!doc/**'

jobs:
  build-s2e:
    name: Build S2E
    runs-on: [self-hosted, nixos, X64]
    steps:
      - uses: actions/checkout@v3
      - name: nix build s2e
        run: |
          nix build -L --accept-flake-config .#s2e

  build-amba-lib:
    name: Build LIBAMBA
    runs-on: [self-hosted, nixos, X64]
    steps:
      - uses: actions/checkout@v3
      - name: nix build libamba
        run: |
          nix build -L --accept-flake-config .#libamba

  build-amba:
    name: Build AMBA
    runs-on: [self-hosted, nixos, X64]
    steps:
      - uses: actions/checkout@v3
      - name: nix build amba
        run: |
          nix build -L --accept-flake-config .#amba

  build-devshell:
    name: Build AMBA devshell
    runs-on: [self-hosted, nixos, X64]
    steps:
      - uses: actions/checkout@v3
      - name: nix build devshell
        run: |
          nix build -L --accept-flake-config .#devShells.x86_64-linux.default

  test-amba-run:
    name: Run AMBA on musl-hello-world
    runs-on: [self-hosted, nixos, X64, impure-persistent-amba-data-dir]
    steps:
      - uses: actions/checkout@v3
      - name: nix run test-amba
        run: |
          nix run -L --accept-flake-config .#test-amba
