name: nix-ci


on:
  push:
    branches:
      - master
      - ci
      - autocxx


jobs:

  build-s2e:
    name: Build S2E
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v20
        with:
          nix_conf: |
            experimental-features = nix-command flakes

      - name: Build Nix flake checks
        run: >
          nix path-info .#s2e --accept-flake-config
	    | tail --bytes +11
	    | head --bytes +33
	    | sed 's|^|https://nix.u3836.se|'
	    | sed 's|$|.narinfo|'
	    | xargs curl
	    | grep "File not found."
	  || nix build -L --accept-flake-config .#s2e

  build-amba:
    name: Build AMBA
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v20
        with:
          nix_conf: |
            experimental-features = nix-command flakes

      - name: Build Nix flake checks
        run: |
        run: >
          nix path-info .#amba --accept-flake-config
	    | tail --bytes +11
	    | head --bytes +33
	    | sed 's|^|https://nix.u3836.se|'
	    | sed 's|$|.narinfo|'
	    | xargs curl
	    | grep "File not found."
	  || nix build -L --accept-flake-config .#amba
