# NOTE: Our CI runs on a persistent nix-enabled self hosted server.
# NOTE: Talk to Loke before/when doing significant changes to the CI workload.

name: self-hosted-nix-ci

on:
  push:
    paths:
      - 'crates/**'
      - 'nix/**'
      - 'demos/**'
      - 'Cargo.lock'
      - 'Cargo.nix'
      - 'Cargo.toml'
      - 'flake.lock'
      - 'flake.nix'

jobs:
  build-s2e:
    name: Build S2E
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build s2e
        run: |
          nix build -L --accept-flake-config .#s2e

  build-amba-lib:
    name: Build LIBAMBA
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build libamba
        run: |
          nix build -L --accept-flake-config .#libamba

  build-amba:
    name: Build AMBA
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build amba
        run: |
          nix build -L --accept-flake-config .#amba

  build-devshell:
    name: Build AMBA devshell
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build devshell
        run: |
          nix build -L --accept-flake-config .#devShells.x86_64-linux.default

  test-amba-run-hello:
    name: Run AMBA on musl-hello-world
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix run test-amba-hello
        run: |
          nix run -L --accept-flake-config .#test-amba-hello

  test-amba-run-control-flow:
    name: Run AMBA on musl-control-flow
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix run test-amba-control-flow
        run: |
          nix run -L --accept-flake-config .#test-amba-control-flow
