name: self-hosted-nix-ci

on: push

jobs:
  build-s2e:
    name: Build S2E
    runs-on: [self-hosted, nixos]

    steps:
      - uses: actions/checkout@v3

      - name: Build Nix flake checks
        run: |
          nix build -L --accept-flake-config .#s2e

  build-amba:
    name: Build AMBA
    runs-on: [self-hosted, nixos]

    steps:
      - uses: actions/checkout@v3

      - name: Build Nix flake checks
        run: |
          nix build -L --accept-flake-config .#amba

  build-amba-lib:
    name: Build LIBAMBA
    runs-on: [self-hosted, nixos]

    steps:
      - uses: actions/checkout@v3

      - name: Build Nix flake checks
        run: |
          nix build -L --accept-flake-config .#libamba
